name: Publish blog

on: [push]

jobs:
  publish:
    name: Generate page
    runs-on: ubuntu-latest
    steps:
      - name: Install requirements
        run: |
          apt install -y nodejs npm
          npm install -g hexo-cli
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Prepare hexo
        run: |
          git clone -b hexo https://github.com/Yikun/yikun.github.com.git
          pushd yikun.github.com
          npm install
      - name: Init yilia
        run: |
          pushd yikun.github.com
          git clone https://github.com/litten/hexo-theme-yilia.git themes/yilia
          cp theme_config.yml themes/yilia/_config.yml
      - name: Update config
        run: |
          pushd yikun.github.com
          sed -i'' "/^ *repo/s~github\.com~${{ secrets.hexo_token }}@github.com~" _config.yml
          popd
      - name: Generate page
        run: |
          pushd yikun.github.com
          hexo migrate github-issue Yikun/yikun.github.com
          hexo clean
          hexo generate
          popd
      - name: Publish
        run: |
          pushd yikun.github.com
          git config --global user.name "Yikun"
          git config --global user.email "yikunkero@gmail.com"
          hexo deploy
          popd
